// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMDxagAPdiAQ_9oIrLF80913KRcLuetw8',
    appId: '1:52856553378:web:3e249b2d342e060a02fcfb',
    messagingSenderId: '52856553378',
    projectId: 'tilang-online-d4b5d',
    authDomain: 'tilang-online-d4b5d.firebaseapp.com',
    storageBucket: 'tilang-online-d4b5d.appspot.com',
    measurementId: 'G-83SHP22RHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6hUndRnZwvAi4r14fCZuqOAEpCGsMpNA',
    appId: '1:52856553378:android:7ee85199be3a78b302fcfb',
    messagingSenderId: '52856553378',
    projectId: 'tilang-online-d4b5d',
    storageBucket: 'tilang-online-d4b5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQycM1-D_w3mzwP1TsA6HOSYyp-dNpkS0',
    appId: '1:52856553378:ios:ac334f7cb6ba6d2e02fcfb',
    messagingSenderId: '52856553378',
    projectId: 'tilang-online-d4b5d',
    storageBucket: 'tilang-online-d4b5d.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQycM1-D_w3mzwP1TsA6HOSYyp-dNpkS0',
    appId: '1:52856553378:ios:ac334f7cb6ba6d2e02fcfb',
    messagingSenderId: '52856553378',
    projectId: 'tilang-online-d4b5d',
    storageBucket: 'tilang-online-d4b5d.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMDxagAPdiAQ_9oIrLF80913KRcLuetw8',
    appId: '1:52856553378:web:5e906dcf49b52fe402fcfb',
    messagingSenderId: '52856553378',
    projectId: 'tilang-online-d4b5d',
    authDomain: 'tilang-online-d4b5d.firebaseapp.com',
    storageBucket: 'tilang-online-d4b5d.appspot.com',
    measurementId: 'G-G2JMV7E0JL',
  );
}
